name: Deploy to AWS Lambda

on:
    push:
        branches:
            - main # Deploy when changes are pushed to the main branch

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the repository
            - name: Checkout Code
              uses: actions/checkout@v3

            # Step 2: Install dependencies
            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            # Step 3: Build the application
            - name: Build Application
              run: yarn build

            # Step 4: Package for Lambda
            - name: Package for Lambda
              run: |
                  mkdir connectrix-server-lambda-package
                  cp -r .next public node_modules package.json yarn.lock connectrix-server-lambda-package/
                  cd connectrix-server-lambda-package
                  zip -r ../connectrix-server-lambda-package.zip .
                  cd ..
                  ls -l connectrix-server-lambda-package.zip

            # Step 5: Upload to S3
            - name: Upload to S3
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
              run: |
                  aws s3 cp connectrix-server-lambda-package.zip s3://connectrix-server/connectrix-server-lambda-package.zip

            # Step 5: Deploy to AWS Lambda
            - name: Deploy to AWS Lambda
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
              run: |
                  aws lambda update-function-code \
                    --function-name connectrix-server \
                    --s3-bucket connectrix-server \
                    --s3-key connectrix-server-lambda-package.zip
